name: ecommerce
description: A new E-Commerce App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  auto_route: ^3.2.4
  dartz: ^0.10.1
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.3
  image_picker: ^0.8.5
  image_cropper: ^2.0.2
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.1.6
  cached_network_image: ^3.2.0
  flutter_custom_clippers: ^2.0.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  rename: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  #  mocktail: ^0.3.0
  mockito: ^5.1.0

  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  auto_route_generator: ^3.2.3
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

