name: ecommerce
description: A new E-Commerce App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  freezed_annotation: ^1.1.0
  auto_route: ^3.2.4
  dartz: ^0.10.1
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.3
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.1.5
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  auto_route_generator: ^3.2.3
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

